const DATABASE_NAME = '@gameplay';

const COLLECTION_USER = `${DATABASE_NAME}:user`;
const COLLECTINO_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLECTION_USER,
    COLLECTINO_APPOINTMENTS
}